-- OurAirports-derived reference data (davidmegginson.github.io/ourairports-data/airports.csv).
-- Populated by the backend sync job; separate from legacy fgs_airport (no coordinates).

CREATE TABLE IF NOT EXISTS public.fgs_airports (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ourairports_id integer NOT NULL,
    icao character varying(8) NOT NULL,
    name text NOT NULL,
    latitude_deg double precision NOT NULL,
    longitude_deg double precision NOT NULL,
    airport_type character varying(40),
    imported_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT fgs_airports_icao_key UNIQUE (icao)
);

CREATE INDEX IF NOT EXISTS fgs_airports_icao_idx ON public.fgs_airports (icao);
