-- Per-author star ratings for published models (1–5 stars, one rating per author per model).

CREATE TABLE IF NOT EXISTS public.fgs_model_ratings (
  mrt_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mrt_model_id   integer NOT NULL REFERENCES public.fgs_models (mo_id) ON DELETE CASCADE,
  mrt_author_id  integer NOT NULL REFERENCES public.fgs_authors (au_id) ON DELETE CASCADE,
  mrt_score      smallint NOT NULL CHECK (mrt_score >= 1 AND mrt_score <= 5),
  mrt_created_at timestamptz NOT NULL DEFAULT now(),
  mrt_updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (mrt_model_id, mrt_author_id)
);

CREATE INDEX IF NOT EXISTS idx_mrt_model ON public.fgs_model_ratings (mrt_model_id);
CREATE INDEX IF NOT EXISTS idx_mrt_author ON public.fgs_model_ratings (mrt_author_id);

COMMENT ON TABLE public.fgs_model_ratings IS 'User star ratings for scenery models; one row per author per model';
